@ReactApp1.Server_HostAddress = http://localhost:5068

GET {{ReactApp1.Server_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{ReactApp1.Server_HostAddress}}/api/
Accept: application/json